/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grafica;

import dto.Vehiculo;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import logica.Registro;
import utilidades.GArchivos;

/**
 *
 * @author WINDOWS10PRO
 */
public class Ventana extends javax.swing.JFrame {

    DefaultTableModel modelo;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btg1 = new javax.swing.ButtonGroup();
        opIngreso = new javax.swing.JRadioButton();
        opSalida = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        cjIdentificacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cjPlaca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cjHora = new javax.swing.JTextField();
        btGuardar = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        cjFecha = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btg1.add(opIngreso);
        opIngreso.setText("Ingreso");
        opIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opIngresoActionPerformed(evt);
            }
        });
        opIngreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                opIngresoKeyReleased(evt);
            }
        });
        getContentPane().add(opIngreso);
        opIngreso.setBounds(40, 10, 120, 25);

        btg1.add(opSalida);
        opSalida.setText("Salida");
        opSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(opSalida);
        opSalida.setBounds(40, 40, 120, 25);

        jLabel1.setText("Identificación");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 90, 90, 20);

        cjIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjIdentificacionActionPerformed(evt);
            }
        });
        getContentPane().add(cjIdentificacion);
        cjIdentificacion.setBounds(20, 120, 140, 20);

        jLabel2.setText("Placa");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 90, 60, 20);
        getContentPane().add(cjPlaca);
        cjPlaca.setBounds(200, 120, 130, 20);

        jLabel3.setText("Fecha");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(420, 90, 60, 20);

        jLabel4.setText("Hora");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(580, 90, 50, 16);
        getContentPane().add(cjHora);
        cjHora.setBounds(540, 120, 120, 22);

        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btGuardar);
        btGuardar.setBounds(30, 180, 90, 25);

        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btSalir);
        btSalir.setBounds(150, 180, 80, 25);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 220, 570, 230);
        getContentPane().add(cjFecha);
        cjFecha.setBounds(370, 120, 140, 20);

        setSize(new java.awt.Dimension(733, 505));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cjIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjIdentificacionActionPerformed
        
    }//GEN-LAST:event_cjIdentificacionActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        //JOptionPane.showMessageDialog(this, "Su vehículo se registró");
        //Date date = jdcFecha.getDate();
        //SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        //String date = formato.format(jdcFecha.getDate());

        if (opIngreso.isSelected()) {
            this.registrarVehiculo();
        }  else if(opSalida.isSelected()){
            JOptionPane.showMessageDialog(this, "Puede retirar su vehiculo");
        }
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSalirActionPerformed

    private void opIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opIngresoActionPerformed

    private void opSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opSalidaActionPerformed

    }//GEN-LAST:event_opSalidaActionPerformed

    private void opIngresoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_opIngresoKeyReleased
        if (opIngreso.isSelected()) {
            cjIdentificacion.setEnabled(true);
        } else if (opIngreso.isSelected()) {
            cjIdentificacion.setEnabled(false);
        }
    }//GEN-LAST:event_opIngresoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    private ArrayList listagestion = new ArrayList();

    public void registrarVehiculo() {
        Calendar calendario = Calendar.getInstance();
        int hora = calendario.get(Calendar.HOUR_OF_DAY);
        int minutos = calendario.get(Calendar.MINUTE);
        String placa = cjPlaca.getText();
        Date fecha = cjFecha.getDate();
        String identificacion = cjIdentificacion.getText();
        Registro a = new Registro();
        Vehiculo nuevoVehiculo = new Vehiculo ();
        nuevoVehiculo = a.crearVehiculo(placa, fecha, hora + ":" + minutos, identificacion);
        listagestion.add(nuevoVehiculo);
        boolean b = GArchivos.guardar("listaVehiculos.pq", listagestion);
         ArrayList vehiculos = (ArrayList)GArchivos.leer("listaVehiculos.pq");
        JOptionPane.showMessageDialog(this, "Su vehículo fue registrado");
    }
    
    private void cargarVehiculo() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Identificación");
        modelo.addColumn("Placa");
        modelo.addColumn("Fecha");
        modelo.addColumn("Hora");
        this.tabla.setModel(modelo);
    
    }
    
        


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btSalir;
    private javax.swing.ButtonGroup btg1;
    private com.toedter.calendar.JDateChooser cjFecha;
    private javax.swing.JTextField cjHora;
    private javax.swing.JTextField cjIdentificacion;
    private javax.swing.JTextField cjPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton opIngreso;
    private javax.swing.JRadioButton opSalida;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
