/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grafica;

/**
 *
 * @author WINDOWS10PRO
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opIngreso = new javax.swing.JRadioButton();
        opSalida = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        cjIdentificacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cjPlaca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cjFecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cjHora = new javax.swing.JTextField();
        btGuardar = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        opIngreso.setText("Ingreso");
        getContentPane().add(opIngreso);
        opIngreso.setBounds(40, 10, 65, 25);

        opSalida.setText("Salida");
        getContentPane().add(opSalida);
        opSalida.setBounds(40, 40, 57, 25);

        jLabel1.setText("Identificación");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 90, 90, 20);
        getContentPane().add(cjIdentificacion);
        cjIdentificacion.setBounds(20, 120, 140, 20);

        jLabel2.setText("Placa");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 90, 60, 20);
        getContentPane().add(cjPlaca);
        cjPlaca.setBounds(200, 120, 130, 20);

        jLabel3.setText("Fecha");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(420, 90, 60, 20);
        getContentPane().add(cjFecha);
        cjFecha.setBounds(370, 120, 130, 22);

        jLabel4.setText("Hora");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(580, 90, 50, 16);
        getContentPane().add(cjHora);
        cjHora.setBounds(540, 120, 120, 22);

        btGuardar.setText("Guardar");
        getContentPane().add(btGuardar);
        btGuardar.setBounds(30, 180, 75, 25);

        btSalir.setText("Salir");
        getContentPane().add(btSalir);
        btSalir.setBounds(130, 180, 80, 25);

        setSize(new java.awt.Dimension(733, 286));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btSalir;
    private javax.swing.JTextField cjFecha;
    private javax.swing.JTextField cjHora;
    private javax.swing.JTextField cjIdentificacion;
    private javax.swing.JTextField cjPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton opIngreso;
    private javax.swing.JRadioButton opSalida;
    // End of variables declaration//GEN-END:variables
}
